{ inputs, ... }:
{
  perSystem =
    {
      self',
      pkgs,
      system,
      ...
    }:
    let
      sdk = import ./_android-sdk.nix { inherit pkgs; };
    in
    {
      devShells = {
        default = pkgs.mkShell rec {
          name = "Android devshell";
          packages = [
            sdk.androidSdk
            sdk.platformTools
            pkgs.jdk
            pkgs.apksigner
            (pkgs.android-studio.withSdk sdk.androidComposition.androidsdk)
            inputs.gradle2nix.packages.${system}.default
          ];
          LANG = "C.UTF-8";
          LC_ALL = "C.UTF-8";
          JAVA_HOME = pkgs.jdk.home;

          # Note: ANDROID_HOME is deprecated. Use ANDROID_SDK_ROOT.
          ANDROID_SDK_ROOT = "${sdk.androidSdk}/libexec/android-sdk";
          ANDROID_NDK_ROOT = "${ANDROID_SDK_ROOT}/ndk-bundle";

          shellHook = ''
            export REPO_ROOT=$(git rev-parse --show-toplevel)
            mkdir -p "$REPO_ROOT/src"

            # Ensures that we don't have to use a FHS env by using the nix store's aapt2.
            export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$(echo "$ANDROID_SDK_ROOT/build-tools/"*"/aapt2")"

            # Add cmake to the path.
            cmake_root="$(echo "$ANDROID_SDK_ROOT/cmake/"*/)"
            export PATH="$cmake_root/bin:$PATH"

            # Write out local.properties for Android Studio.
            cat <<EOF > "$REPO_ROOT/local.properties"
            # This file was automatically generated by nix-shell.
            sdk.dir=$ANDROID_SDK_ROOT
            ndk.dir=$ANDROID_NDK_ROOT
            cmake.dir=$cmake_root
            EOF

            cp "$REPO_ROOT/local.properties" "$REPO_ROOT/src"
          '';
        };
      };
    };
}
