{ inputs, ... }:
{
  perSystem =
    {
      self',
      pkgs,
      ...
    }:
    {
      devShells = {
        default =
          let
            includeAuto = pkgs.stdenv.hostPlatform.isx86_64 || pkgs.stdenv.hostPlatform.isDarwin;

            ndkVersions = [
              "latest"
            ];
            androidComposition = pkgs.androidenv.composeAndroidPackages {
              includeSources = true;
              includeSystemImages = false;
              includeEmulator = "if-supported";
              includeNDK = "if-supported";
              inherit ndkVersions;
              useGoogleAPIs = true;
              useGoogleTVAddOns = true;

              numLatestPlatformVersions = 10;

              includeExtras = [
                "extras;google;gcm"
              ]
              ++ pkgs.lib.optionals includeAuto [
                "extras;google;auto"
              ];

              extraLicenses = [
                # Already accepted for you with the global accept_license = true or
                # licenseAccepted = true on androidenv.
                # "android-sdk-license"

                # These aren't, but are useful for more uncommon setups.
                "android-sdk-preview-license"
                "android-googletv-license"
                "android-sdk-arm-dbt-license"
                "google-gdk-license"
                "intel-android-extra-license"
                "intel-android-sysimage-license"
                "mips-android-sysimage-license"
              ];
            };
            androidSdk = androidComposition.androidsdk;
            platformTools = androidComposition.platform-tools;
            firstSdk = pkgs.lib.foldl' pkgs.lib.min 100 androidComposition.platformVersions;
            latestSdk = pkgs.lib.foldl' pkgs.lib.max 0 androidComposition.platformVersions;
            jdk = pkgs.jdk;
          in
          pkgs.mkShell rec {
            name = "Android devshell";
            packages = [
              androidSdk
              platformTools
              jdk
              (pkgs.android-studio.withSdk androidComposition.androidsdk)
            ];
            LANG = "C.UTF-8";
            LC_ALL = "C.UTF-8";
            JAVA_HOME = jdk.home;

            # Note: ANDROID_HOME is deprecated. Use ANDROID_SDK_ROOT.
            ANDROID_SDK_ROOT = "${androidSdk}/libexec/android-sdk";
            ANDROID_NDK_ROOT = "${ANDROID_SDK_ROOT}/ndk-bundle";

            shellHook = ''
              # Ensures that we don't have to use a FHS env by using the nix store's aapt2.
              export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$(echo "$ANDROID_SDK_ROOT/build-tools/"*"/aapt2")"

              # Add cmake to the path.
              cmake_root="$(echo "$ANDROID_SDK_ROOT/cmake/"*/)"
              export PATH="$cmake_root/bin:$PATH"

              # Write out local.properties for Android Studio.
              cat <<EOF > local.properties
              # This file was automatically generated by nix-shell.
              sdk.dir=$ANDROID_SDK_ROOT
              ndk.dir=$ANDROID_NDK_ROOT
              cmake.dir=$cmake_root
              EOF
            '';
          };
      };
    };
}
